brew "mas"
mas "ZSA Keymapp", id: 6472865291

brew "defaultbrowser"
brew "dockutil"
brew "git-lfs"

cask "alacritty"
cask "balenaetcher"
cask "chromium"
cask "discord"
cask "font-3270-nerd-font"
cask "obsidian"
cask "orion"
cask "podman-desktop"
cask "raycast"
cask "steam"
cask "vlc"
cask "zed"
